packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'packages/shared/*'
  - 'packages/extensions/*'
  # all packages in subdirs of components/
  # - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

overrides:
  '@types/ws': '8.5.4'
  # 'vite': 'npm:rolldown-vite@latest'
  'depd': 'latest'
  'node-abi': 'latest'
  'json5': 'latest'
  'semver': 'latest'
  'minimatch': 'latest'
  'micromatch': 'latest'
  'postcss': 'latest'
  'ws>bufferutil': '-'
  'ws>utf-8-validate': '-'
  'tmp@<=0.2.3': '>=0.2.4'
  'tar-fs@>=2.0.0 <2.1.4': '>=2.1.4'

# https://github.com/pnpm/pnpm/issues/8378
publicHoistPattern:
  - '*eslint*'
# minimumReleaseAge: 480
# minimumReleaseAgeExclude:
#   - typescript
#   - undici
#   - message2call
#   - better-sqlite3
#   - '@types/node'
#   - svelte
#   - svelte-check
#   - svelte-eslint-parser
#   - svelte-preprocess
#   - '@sveltejs/vite-plugin-svelte'
#   - eslint-plugin-svelte
#   - electron
#   - electron-builder
#   - electron-updater
#   - electron-to-chromium
#   - prettier-plugin-organize-imports
#   - npm-check-updates
