name: Development

on:
  push:
    branches:
      - dev3
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 QEMU 支持（用于跨架构构建）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 设置变量（小写镜像名 & 大写 TAR 文件名，添加 darwin_arm64 标识）
      - name: Set image name variables
        run: |
          SHORT_SHA=$(git rev-parse --short=7 HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "IMAGE_NAME=any_listen_$SHORT_SHA" >> $GITHUB_ENV
          echo "TAR_NAME=Any_listen_darwin_arm64_$SHORT_SHA.tar" >> $GITHUB_ENV

      # 构建 Docker 镜像（指定为 linux/arm64 架构）
      - name: Build Docker Image for darwin arm64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --output type=docker \
            -t $IMAGE_NAME .

      # 保存 Docker 镜像为 TAR 文件
      - name: Save Docker Image as TAR
        run: |
          docker save -o $TAR_NAME $IMAGE_NAME

      # 上传 TAR 文件到 GitHub Releases
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.SHORT_SHA }}
          name: Release for commit ${{ env.SHORT_SHA }}
          files: ${{ env.TAR_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
